export const WITHHOLD_STATUS = 'WITHHOLD_STATUS';           // 代扣状态
export const REPAYMENT_STATUS = 'REPAYMENT_STATUS';         // 还款状态
export const REPAYMENT_METHOD = 'REPAYMENT_METHOD';         // 分配方式
export const PARTNER = 'PARTNER';                           // 渠道合作方
export const OVERDUE_STATUS = 'OVERDUE_STATUS';             // 逾期状态
export const COMPENSATORY_STATUS = 'COMPENSATORY_STATUS';   // 代偿状态
export const PROVINCE = 'PROVINCE';                         // 省
export const CITY = 'CITY';                                 // 市
export const DISTRICT = 'DISTRICT';                         // 区
export const RESET_DISTRICT = 'RESET_DISTRICT';
export const BANK_LIST = 'BANK_LIST';                       // 银行列表
export const PRODUCT_TYPE = 'PRODUCT_TYPE';                 // 产品类型
export const CONTACT_STATUS = 'CONTACT_STATUS';             // 可联状态
export const TRACKER = 'TRACKER';                           // 催服专员
export const CASE_TRACK_TYPE = 'CASE_TRACK_TYPE';           // 催记类型
